### ISSUE TITLE
Tracking Issue: Make test suite pass on alpine

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#1753]
For better musl support, we should add alpine to CI. The first step to that is making the test suite pass on alpine. We are currently at 8 failures. Each test failure needs to be triaged and either fixed or the test ignored. Afterwards, we need a script that we can run on github actions and need to integrate it with caching.

- [ ] uv-interpreter interpreter::tests::test_cache_invalidation
- [ ] uv::pip_install install_executable
- [ ] uv::pip_install install_executable_copy
- [ ] uv::pip_install install_executable_hardlink
- [ ] uv::pip_install install_pinned_polars_invalid_metadata
- [ ] uv::pip_sync install_numpy_py38
- [ ] uv::pip_sync install_ujson
- [ ] uv::pip_sync sync_editable

The alpine environment:

```
docker run --rm -it -v $(pwd):/io alpine
```

```
set -e

cd /io
# cmake gcc make musl-dev openssl-dev rustup are require for building uv itself
# python3 py3-zstandard are for the bootstrap script
# TODO(konstin): Check if we need the others
apk add alpine-sdk cmake gcc make musl-dev openssl-dev perl python3 py3-zstandard rustup
python3 scripts/bootstrap/install.py
rustup-init -t x86_64-unknown-linux-musl --default-toolchain none -y
# https://github.com/nextest-rs/nextest/issues/1326
curl -LsSf https://github.com/nextest-rs/nextest/releases/download/cargo-nextest-0.9.67/cargo-nextest-0.9.67-x86_64-unknown-linux-musl.tar.gz | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
CARGO_TARGET_DIR=target-alpine $HOME/.cargo/bin/cargo nextest run --failure-output immediate-final --no-fail-fast
```

Feel free to update this issue as we progress.

<details>
  <summary>Detailed test log</summary>

     Summary [  33.069s] 507 tests run: 499 passed (20 slow), 8 failed, 2 skipped
        FAIL [   0.004s] uv-interpreter interpreter::tests::test_cache_invalidation

--- STDOUT:              uv-interpreter interpreter::tests::test_cache_invalidation ---

running 1 test
test interpreter::tests::test_cache_invalidation ... FAILED

failures:

failures:
    interpreter::tests::test_cache_invalidation

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.00s

--- STDERR:              uv-interpreter interpreter::tests::test_cache_invalidation ---
thread 'interpreter::tests::test_cache_invalidation' panicked at crates/uv-interpreter/src/interpreter.rs:485:86:
called `Result::unwrap()` on an `Err` value: PythonSubcommandLaunch { interpreter: "/tmp/.tmpRUkcsh/python", err: Os { code: 2, kind: NotFound, message: "No such file or directory" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

        FAIL [   4.310s] uv::pip_install install_executable

--- STDOUT:              uv::pip_install install_executable ---

running 1 test
test install_executable ... FAILED

failures:

failures:
    install_executable

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 22 filtered out; finished in 4.31s

--- STDERR:              uv::pip_install install_executable ---
thread 'install_executable' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=1
stderr=``````
Traceback (most recent call last):
  File \"/tmp/.tmpyIeF0m/.venv/bin/pylint\", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File \"/tmp/.tmpyIeF0m/.venv/lib/python3.12/site-packages/pylint/__init__.py\", line 31, in run_pylint
    from pylint.lint import Run as PylintRun
  File \"/tmp/.tmpyIeF0m/.venv/lib/python3.12/site-packages/pylint/lint/__init__.py\", line 22, in <module>
    from pylint.lint.parallel import check_parallel
  File \"/tmp/.tmpyIeF0m/.venv/lib/python3.12/site-packages/pylint/lint/parallel.py\", line 12, in <module>
    import dill
  File \"/tmp/.tmpyIeF0m/.venv/lib/python3.12/site-packages/dill/__init__.py\", line 26, in <module>
    from ._dill import (
  File \"/tmp/.tmpyIeF0m/.venv/lib/python3.12/site-packages/dill/_dill.py\", line 1995, in <module>
    _PyCapsule_New = ctypes.pythonapi.PyCapsule_New
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: \'NoneType\' object has no attribute \'PyCapsule_New\'
```
```
command=`"/tmp/.tmpyIeF0m/.venv/bin/pylint" "--version"`
code=1
stdout=""
stderr=```
Traceback (most recent call last):
  File \"/tmp/.tmpyIeF0m/.venv/bin/pylint\", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File \"/tmp/.tmpyIeF0m/.venv/lib/python3.12/site-packages/pylint/__init__.py\", line 31, in run_pylint
    from pylint.lint import Run as PylintRun
  File \"/tmp/.tmpyIeF0m/.venv/lib/python3.12/site-packages/pylint/lint/__init__.py\", line 22, in <module>
    from pylint.lint.parallel import check_parallel
  File \"/tmp/.tmpyIeF0m/.venv/lib/python3.12/site-packages/pylint/lint/parallel.py\", line 12, in <module>
    import dill
  File \"/tmp/.tmpyIeF0m/.venv/lib/python3.12/site-packages/dill/__init__.py\", line 26, in <module>
    from ._dill import (
  File \"/tmp/.tmpyIeF0m/.venv/lib/python3.12/site-packages/dill/_dill.py\", line 1995, in <module>
    _PyCapsule_New = ctypes.pythonapi.PyCapsule_New
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: \'NoneType\' object has no attribute \'PyCapsule_New\'
```


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

        FAIL [   1.823s] uv::pip_install install_executable_copy

--- STDOUT:              uv::pip_install install_executable_copy ---

running 1 test
test install_executable_copy ... FAILED

failures:

failures:
    install_executable_copy

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 22 filtered out; finished in 1.82s


--- STDERR:              uv::pip_install install_executable_copy ---
thread 'install_executable_copy' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=1
stderr=``````
Traceback (most recent call last):
  File \"/tmp/.tmpglKMOm/.venv/bin/pylint\", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File \"/tmp/.tmpglKMOm/.venv/lib/python3.12/site-packages/pylint/__init__.py\", line 31, in run_pylint
    from pylint.lint import Run as PylintRun
  File \"/tmp/.tmpglKMOm/.venv/lib/python3.12/site-packages/pylint/lint/__init__.py\", line 22, in <module>
    from pylint.lint.parallel import check_parallel
  File \"/tmp/.tmpglKMOm/.venv/lib/python3.12/site-packages/pylint/lint/parallel.py\", line 12, in <module>
    import dill
  File \"/tmp/.tmpglKMOm/.venv/lib/python3.12/site-packages/dill/__init__.py\", line 26, in <module>
    from ._dill import (
  File \"/tmp/.tmpglKMOm/.venv/lib/python3.12/site-packages/dill/_dill.py\", line 1995, in <module>
    _PyCapsule_New = ctypes.pythonapi.PyCapsule_New
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: \'NoneType\' object has no attribute \'PyCapsule_New\'
```
```
command=`"/tmp/.tmpglKMOm/.venv/bin/pylint" "--version"`
code=1
stdout=""
stderr=```
Traceback (most recent call last):
  File \"/tmp/.tmpglKMOm/.venv/bin/pylint\", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File \"/tmp/.tmpglKMOm/.venv/lib/python3.12/site-packages/pylint/__init__.py\", line 31, in run_pylint
    from pylint.lint import Run as PylintRun
  File \"/tmp/.tmpglKMOm/.venv/lib/python3.12/site-packages/pylint/lint/__init__.py\", line 22, in <module>
    from pylint.lint.parallel import check_parallel
  File \"/tmp/.tmpglKMOm/.venv/lib/python3.12/site-packages/pylint/lint/parallel.py\", line 12, in <module>
    import dill
  File \"/tmp/.tmpglKMOm/.venv/lib/python3.12/site-packages/dill/__init__.py\", line 26, in <module>
    from ._dill import (
  File \"/tmp/.tmpglKMOm/.venv/lib/python3.12/site-packages/dill/_dill.py\", line 1995, in <module>
    _PyCapsule_New = ctypes.pythonapi.PyCapsule_New
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: \'NoneType\' object has no attribute \'PyCapsule_New\'
```

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

        FAIL [   4.233s] uv::pip_install install_executable_hardlink

--- STDOUT:              uv::pip_install install_executable_hardlink ---

running 1 test
test install_executable_hardlink ... FAILED

failures:

failures:
    install_executable_hardlink

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 22 filtered out; finished in 4.23s

--- STDERR:              uv::pip_install install_executable_hardlink ---
thread 'install_executable_hardlink' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=1
stderr=``````
Traceback (most recent call last):
  File \"/tmp/.tmpdoPvFr/.venv/bin/pylint\", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File \"/tmp/.tmpdoPvFr/.venv/lib/python3.12/site-packages/pylint/__init__.py\", line 31, in run_pylint
    from pylint.lint import Run as PylintRun
  File \"/tmp/.tmpdoPvFr/.venv/lib/python3.12/site-packages/pylint/lint/__init__.py\", line 22, in <module>
    from pylint.lint.parallel import check_parallel
  File \"/tmp/.tmpdoPvFr/.venv/lib/python3.12/site-packages/pylint/lint/parallel.py\", line 12, in <module>
    import dill
  File \"/tmp/.tmpdoPvFr/.venv/lib/python3.12/site-packages/dill/__init__.py\", line 26, in <module>
    from ._dill import (
  File \"/tmp/.tmpdoPvFr/.venv/lib/python3.12/site-packages/dill/_dill.py\", line 1995, in <module>
    _PyCapsule_New = ctypes.pythonapi.PyCapsule_New
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: \'NoneType\' object has no attribute \'PyCapsule_New\'
```
```
command=`"/tmp/.tmpdoPvFr/.venv/bin/pylint" "--version"`
code=1
stdout=""
stderr=```
Traceback (most recent call last):
  File \"/tmp/.tmpdoPvFr/.venv/bin/pylint\", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File \"/tmp/.tmpdoPvFr/.venv/lib/python3.12/site-packages/pylint/__init__.py\", line 31, in run_pylint
    from pylint.lint import Run as PylintRun
  File \"/tmp/.tmpdoPvFr/.venv/lib/python3.12/site-packages/pylint/lint/__init__.py\", line 22, in <module>
    from pylint.lint.parallel import check_parallel
  File \"/tmp/.tmpdoPvFr/.venv/lib/python3.12/site-packages/pylint/lint/parallel.py\", line 12, in <module>
    import dill
  File \"/tmp/.tmpdoPvFr/.venv/lib/python3.12/site-packages/dill/__init__.py\", line 26, in <module>
    from ._dill import (
  File \"/tmp/.tmpdoPvFr/.venv/lib/python3.12/site-packages/dill/_dill.py\", line 1995, in <module>
    _PyCapsule_New = ctypes.pythonapi.PyCapsule_New
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: \'NoneType\' object has no attribute \'PyCapsule_New\'
```


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

        FAIL [   2.197s] uv::pip_install install_pinned_polars_invalid_metadata

--- STDOUT:              uv::pip_install install_pinned_polars_invalid_metadata ---

running 1 test
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: install_pinned_polars_invalid_metadata
Source: crates/uv/tests/pip_install.rs:1176
────────────────────────────────────────────────────────────────────────────────
Expression: snapshot
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0       │-success: true␊
    1       │-exit_code: 0␊
          0 │+success: false␊
          1 │+exit_code: 2␊
    2     2 │ ----- stdout -----␊
    3     3 │ ␊
    4     4 │ ----- stderr -----␊
    5     5 │ Resolved 1 package in [TIME]␊
    6       │-Downloaded 1 package in [TIME]␊
    7       │-Installed 1 package in [TIME]␊
    8       │- + polars==0.14.0
          6 │+error: Failed to download distributions␊
          7 │+  Caused by: Failed to fetch wheel: polars==0.14.0␊
          8 │+  Caused by: Failed to build: polars==0.14.0␊
          9 │+  Caused by: Invalid pyproject.toml␊
         10 │+  Caused by: TOML parse error at line 15, column 11␊
         11 │+   |␊
         12 │+15 | pyarrow = ["pyarrow>=4.0.*"]␊
         13 │+   |           ^^^^^^^^^^^^^^^^^^␊
         14 │+Operator >= cannot be used with a wildcard version specifier␊
         15 │+pyarrow>=4.0.*␊
         16 │+       ^^^^^^^␊
         17 │+␊
────────────┴───────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
test install_pinned_polars_invalid_metadata ... FAILED

failures:

failures:
    install_pinned_polars_invalid_metadata

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 22 filtered out; finished in 2.19s


--- STDERR:              uv::pip_install install_pinned_polars_invalid_metadata ---
thread 'install_pinned_polars_invalid_metadata' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.34.0/src/runtime.rs:563:9:
snapshot assertion for 'install_pinned_polars_invalid_metadata' failed in line 1176
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

        FAIL [  14.421s] uv::pip_sync install_numpy_py38

--- STDOUT:              uv::pip_sync install_numpy_py38 ---

running 1 test
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: install_numpy_py38
Source: crates/uv/tests/pip_sync.rs:791
────────────────────────────────────────────────────────────────────────────────
Expression: snapshot
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0       │-success: true␊
    1       │-exit_code: 0␊
          0 │+success: false␊
          1 │+exit_code: 2␊
    2     2 │ ----- stdout -----␊
    3     3 │ ␊
    4     4 │ ----- stderr -----␊
    5     5 │ Resolved 1 package in [TIME]␊
    6       │-Downloaded 1 package in [TIME]␊
    7       │-Installed 1 package in [TIME]␊
    8       │- + numpy==1.24.4
          6 │+error: Failed to download distributions␊
          7 │+  Caused by: Failed to fetch wheel: numpy==1.24.4␊
          8 │+  Caused by: Failed to build: numpy==1.24.4␊
          9 │+  Caused by: Build backend failed to build wheel through `build_wheel()`:␊
         10 │+--- stdout:␊
         11 │+Processing numpy/random/_bounded_integers.pxd.in␊
         12 │+Processing numpy/random/_philox.pyx␊
         13 │+Cythonizing sources␊
         14 │+--- stderr:␊
         15 │+Traceback (most recent call last):␊
         16 │+  File "/io/bin/versions/cpython@3.8.18/install/lib/python3.8/runpy.py", line 194, in _run_module_as_main␊
         17 │+    return _run_code(code, main_globals, None,␊
         18 │+  File "/io/bin/versions/cpython@3.8.18/install/lib/python3.8/runpy.py", line 87, in _run_code␊
         19 │+    exec(code, run_globals)␊
         20 │+  File "/tmp/.tmpn1AznX/.tmpAoDXGD/.venv/lib/python3.8/site-packages/cython.py", line 16, in <module>␊
         21 │+    from Cython.Compiler.Main import main␊
         22 │+  File "/tmp/.tmpn1AznX/.tmpAoDXGD/.venv/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 28, in <module>␊
         23 │+    from .Scanning import PyrexScanner, FileSourceDescriptor␊
         24 │+ImportError: Dynamic loading not supported␊
         25 │+Traceback (most recent call last):␊
         26 │+  File "/tmp/.tmpn1AznX/built-wheels-v0/pypi/numpy/1.24.4/MBlyN8Dubi8X5Gr9u8FIn/numpy-1.24.4.tar.gz/tools/cythonize.py", line 205, in <module>␊
         27 │+    main()␊
         28 │+  File "/tmp/.tmpn1AznX/built-wheels-v0/pypi/numpy/1.24.4/MBlyN8Dubi8X5Gr9u8FIn/numpy-1.24.4.tar.gz/tools/cythonize.py", line 201, in main␊
         29 │+    find_process_files(root_dir)␊
         30 │+  File "/tmp/.tmpn1AznX/built-wheels-v0/pypi/numpy/1.24.4/MBlyN8Dubi8X5Gr9u8FIn/numpy-1.24.4.tar.gz/tools/cythonize.py", line 192, in find_process_files␊
         31 │+    process(root_dir, fromfile, tofile, function, hash_db)␊
         32 │+  File "/tmp/.tmpn1AznX/built-wheels-v0/pypi/numpy/1.24.4/MBlyN8Dubi8X5Gr9u8FIn/numpy-1.24.4.tar.gz/tools/cythonize.py", line 158, in process␊
         33 │+    processor_function(fromfile, tofile)␊
         34 │+  File "/tmp/.tmpn1AznX/built-wheels-v0/pypi/numpy/1.24.4/MBlyN8Dubi8X5Gr9u8FIn/numpy-1.24.4.tar.gz/tools/cythonize.py", line 47, in process_pyx␊
         35 │+    subprocess.check_call(␊
         36 │+  File "/io/bin/versions/cpython@3.8.18/install/lib/python3.8/subprocess.py", line 364, in check_call␊
         37 │+    raise CalledProcessError(retcode, cmd)␊
         38 │+subprocess.CalledProcessError: Command '['/tmp/.tmpn1AznX/.tmpAoDXGD/.venv/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.␊
         39 │+Running from numpy source directory.␊
         40 │+setup.py:67: DeprecationWarning: ␊
         41 │+␊
         42 │+  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result␊
         43 │+  of the deprecation of `distutils` itself. It will be removed for␊
         44 │+  Python >= 3.12. For older Python versions it will remain present.␊
         45 │+  It is recommended to use `setuptools < 60.0` for those Python versions.␊
         46 │+  For more details, see:␊
         47 │+    https://numpy.org/devdocs/reference/distutils_status_migration.html ␊
         48 │+␊
         49 │+␊
         50 │+  import numpy.distutils.command.sdist␊
         51 │+Traceback (most recent call last):␊
         52 │+  File "<string>", line 6, in <module>␊
         53 │+  File "/tmp/.tmpn1AznX/.tmpAoDXGD/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 230, in build_wheel␊
         54 │+    return self._build_with_temp_dir(['bdist_wheel'], '.whl',␊
         55 │+  File "/tmp/.tmpn1AznX/.tmpAoDXGD/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir␊
         56 │+    self.run_setup()␊
         57 │+  File "/tmp/.tmpn1AznX/.tmpAoDXGD/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 267, in run_setup␊
         58 │+    super(_BuildMetaLegacyBackend,␊
         59 │+  File "/tmp/.tmpn1AznX/.tmpAoDXGD/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup␊
         60 │+    exec(compile(code, __file__, 'exec'), locals())␊
         61 │+  File "setup.py", line 479, in <module>␊
         62 │+    setup_package()␊
         63 │+  File "setup.py", line 458, in setup_package␊
         64 │+    generate_cython()␊
         65 │+  File "setup.py", line 261, in generate_cython␊
         66 │+    raise RuntimeError("Running cythonize failed!")␊
         67 │+RuntimeError: Running cythonize failed!␊
         68 │+---␊
────────────┴───────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
test install_numpy_py38 ... FAILED

failures:

failures:
    install_numpy_py38

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 52 filtered out; finished in 14.42s


--- STDERR:              uv::pip_sync install_numpy_py38 ---
thread 'install_numpy_py38' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.34.0/src/runtime.rs:563:9:
snapshot assertion for 'install_numpy_py38' failed in line 791
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

        FAIL [  16.069s] uv::pip_sync install_ujson

--- STDOUT:              uv::pip_sync install_ujson ---

running 1 test
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: install_ujson
Source: crates/uv/tests/pip_sync.rs:1172
────────────────────────────────────────────────────────────────────────────────
Expression: snapshot
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0       │-success: true␊
    1       │-exit_code: 0␊
          0 │+success: false␊
          1 │+exit_code: 2␊
    2     2 │ ----- stdout -----␊
    3     3 │ ␊
    4     4 │ ----- stderr -----␊
    5     5 │ Resolved 1 package in [TIME]␊
    6       │-Downloaded 1 package in [TIME]␊
    7       │-Installed 1 package in [TIME]␊
    8       │- + ujson==5.7.0 (from https://files.pythonhosted.org/packages/43/1a/b0a027144aa5c8f4ea654f4afdd634578b450807bb70b9f8bad00d6f6d3c/ujson-5.7.0.tar.gz)
          6 │+error: Failed to download distributions␊
          7 │+  Caused by: Failed to fetch wheel: ujson @ https://files.pythonhosted.org/packages/43/1a/b0a027144aa5c8f4ea654f4afdd634578b450807bb70b9f8bad00d6f6d3c/ujson-5.7.0.tar.gz␊
          8 │+  Caused by: Failed to build: ujson @ https://files.pythonhosted.org/packages/43/1a/b0a027144aa5c8f4ea654f4afdd634578b450807bb70b9f8bad00d6f6d3c/ujson-5.7.0.tar.gz␊
          9 │+  Caused by: Build backend failed to build wheel through `build_wheel()`:␊
         10 │+--- stdout:␊
         11 │+running bdist_wheel␊
         12 │+running build␊
         13 │+running build_ext␊
         14 │+building 'ujson' extension␊
         15 │+creating build␊
         16 │+creating build/temp.linux-x86_64-cpython-312␊
         17 │+creating build/temp.linux-x86_64-cpython-312/deps␊
         18 │+creating build/temp.linux-x86_64-cpython-312/deps/double-conversion␊
         19 │+creating build/temp.linux-x86_64-cpython-312/deps/double-conversion/double-conversion␊
         20 │+creating build/temp.linux-x86_64-cpython-312/lib␊
         21 │+creating build/temp.linux-x86_64-cpython-312/python␊
         22 │+musl-clang -fno-strict-overflow -fno-strict-aliasing -DNDEBUG -g -O3 -Wall -fPIC -static -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/tmp/.tmpgP5M6Y/.tmp5NHPVk/.venv/include -I/io/bin/versions/cpython@3.12.1/install/include/python3.12 -c ./deps/double-conversion/double-conversion/bignum-dtoa.cc -o build/temp.linux-x86_64-cpython-312/./deps/double-conversion/double-conversion/bignum-dtoa.o -D_GNU_SOURCE␊
         23 │+--- stderr:␊
         24 │+WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'␊
         25 │+error: command 'musl-clang' failed: No such file or directory␊
         26 │+---␊
────────────┴───────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
test install_ujson ... FAILED

failures:

failures:
    install_ujson

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 52 filtered out; finished in 16.07s


--- STDERR:              uv::pip_sync install_ujson ---
thread 'install_ujson' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.34.0/src/runtime.rs:563:9:
snapshot assertion for 'install_ujson' failed in line 1172
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

        FAIL [  17.430s] uv::pip_sync sync_editable

--- STDOUT:              uv::pip_sync sync_editable ---

running 1 test
test sync_editable ... FAILED

failures:

failures:
    sync_editable

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 52 filtered out; finished in 17.43s


--- STDERR:              uv::pip_sync sync_editable ---
thread 'sync_editable' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=1
stderr=``````
Traceback (most recent call last):
  File \"<string>\", line 1, in <module>
  File \"/io/scripts/editable-installs/maturin_editable/python/maturin_editable/__init__.py\", line 1, in <module>
    from .maturin_editable import *
ImportError: Dynamic loading not supported
```
```
command=`cd "/tmp/.tmpGH0KkP" && "/tmp/.tmpGH0KkP/.venv/bin/python" "-B" "-c" "from maturin_editable import sum_as_string, version\n\nassert version == 1, version\nassert sum_as_string(1, 2) == \"3\", sum_as_string(1, 2)\n"`
code=1
stdout=""
stderr=```
Traceback (most recent call last):
  File \"<string>\", line 1, in <module>
  File \"/io/scripts/editable-installs/maturin_editable/python/maturin_editable/__init__.py\", line 1, in <module>
    from .maturin_editable import *
ImportError: Dynamic loading not supported
```

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: test run failed
```

</summary>

**Comment by konstin** [comment]
See https://github.com/astral-sh/uv/pull/2382 for another problem with alpine/musl

**Comment by konstin** [comment]
This issue doesn't make sense without dynamically linked musl pbs builds, and it should be fixed with them.
